name: 'DDR Security Email Notifications - Email changed'
type: 'Droptica’s Drupal Recipes'
description: "Automatic notifications and logging of user email changes"

install:
  - eca_content
  - eca_ui
  - bpmn_io
  - eca_modeller_bpmn
  - eca_log
  - token
  - user
